#!/bin/bash
ulimit -t 1800
ulimit -v 1500000
export CISSTOPCONT=1
cd /store/nms_informatics_research/planning/planners//home/k1889983/Documents/a-maze/outputDir/
mkdir downwardtmp
cd downwardtmp
/dcs/research/ais/planning/planners/downward /home/k1889983/Documents/a-maze/domain.pddl /home/k1889983/Documents/a-maze/huge.pddl > ../downward
rm output.sas
rm output
rm sas_plan
rm test.groups
cd ..
rmdir downwardtmp
